declare const Mongoose: any;
declare const emailRegex: RegExp;
declare const bsonRegex: RegExp;
declare const urlRegex: RegExp;
declare function isValidName(name: any): boolean;
declare function isValidFunction(func: any): boolean;
declare function isValidText(text: any): boolean;
declare function isValidBool(bool: any): boolean;
declare function isValidDate(date: any): boolean;
declare function isValidEmail(email: any): boolean;
declare function isValidArray(arr: any): boolean;
declare function isValidIdString(testId: any): boolean;
declare function isValidObject(obj: any): boolean;
declare function isValidId(testId: any): boolean;
declare function isValidUrl(url: any): boolean;
declare function isValidInt(num: any): boolean;
declare function isValidNumber(num: any): boolean;
declare function findInvalidIds(ids: any): any[];
declare function getValidateMethodForType(type: any): typeof isValidName;
declare function validateObject(target: any, schema: any): boolean;
