/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript in Alpaca.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Alpaca model and this will regenerate the next time the server starts.
 */

export interface Company {
  name: string;
  industry?: string;
  [k: string]: any;
}
