/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript in Alpaca.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Alpaca model and this will regenerate the next time the server starts.
 */

export interface User {
  first_name: string;
  last_name: string;
  age?: number;
  middle_name?: string;
  company_name: string;
  parent?: {
    [k: string]: any;
  };
  [k: string]: any;
}
